# Generated by Django 4.2.3 on 2023-10-12 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
