# Generated by Django 4.2.3 on 2023-10-13 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0002_delete_tutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='curso',
            new_name='nombre',
        ),
    ]
