# Generated by Django 4.2.3 on 2023-10-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0004_curso_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='usuario',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
