# Generated by Django 4.2.3 on 2023-10-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0006_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='curso_inscripto',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
