# Generated by Django 4.2.5 on 2023-10-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0007_alumno_curso_inscripto'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
